// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmc5AbyxjEfqtnDwU81ME2JrgJI0gyqs0',
    appId: '1:825088100591:web:ae604aa0c90ee12059f31a',
    messagingSenderId: '825088100591',
    projectId: 'transport-a5592',
    authDomain: 'transport-a5592.firebaseapp.com',
    storageBucket: 'transport-a5592.firebasestorage.app',
    measurementId: 'G-676V7J827G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMiePrYgN44br_RKV4CPmiC-zxXNcQqbA',
    appId: '1:825088100591:android:e7106db6493d214059f31a',
    messagingSenderId: '825088100591',
    projectId: 'transport-a5592',
    storageBucket: 'transport-a5592.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmc5AbyxjEfqtnDwU81ME2JrgJI0gyqs0',
    appId: '1:825088100591:web:6a9c8a91a597f90c59f31a',
    messagingSenderId: '825088100591',
    projectId: 'transport-a5592',
    authDomain: 'transport-a5592.firebaseapp.com',
    storageBucket: 'transport-a5592.firebasestorage.app',
    measurementId: 'G-BHYTW154BX',
  );
}
